ALTER TABLE messages ADD COLUMN client_message_id TEXT;
ALTER TABLE messages ADD COLUMN retry_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE messages ADD COLUMN max_retries INTEGER NOT NULL DEFAULT 2;
